Algoritmo "Entrada de dados"
Var
idade: inteiro
salario1,salario2: real
nome: caractere


Inicio
escreva ("Digite seu nome: ")
leia (nome)

escreva ("Digite sua idade: ")
leia (idade)

escreval("Digite o seu salário nos 2 ultimos meses")
leia (salario1)
leia (salario2)

escreval("Dados digitados: ")
escreval("Nome: ",nome)
escreval("Idade: ",idade)
escreval("Salario1: ", salario1:8:2)
escreval("Salario1: ", salario2:8:2)



Fimalgoritmo